services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "472" # runs as the grafana user for safety
    networks:
      - ingress-network
    volumes:
      - ./config:/etc/grafana                   # configuration
      - ${DATA}/grafana/data:/var/lib/grafana   # persistent data
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    labels:
      - "homepage.group=Dashboard"
      - "homepage.name=Grafana"
      - "homepage.icon=grafana"
      - "homepage.href=http://basserver:3000"

networks:
  ingress-network:
    external: true
